### ISSUE TITLE
Add Icons.

### ISSUE THREAD

**Issue by sankhadeeproy007** [GeekyAnts/native-basev3-testbed#2]
Add icons to the components. Use @expo/vector-icons.

**Comment by hanykumar** [comment]
Hi, Icon component has been added.

![Screenshot 2020-04-29 at 1 22 17 PM](https://user-images.githubusercontent.com/15860517/80582999-44c2cd00-8a2d-11ea-8046-9e164d2f2dc6.png)

**Comment by sankhadeeproy007** [comment]
Closed with https://github.com/GeekyAnts/native-basev3-testbed/pull/22
